name: Run Unit Tests

on: [push, pull_request]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4

        with:
          node-version: latest

      - name: Install dependencies
        run: |
            cd ./client
            npm ci

      - name: Run tests
        run: npm test
